# App name
spring.application.name=counselai-backend

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/counselai_db
spring.datasource.username=postgres
spring.datasource.password=123

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8080